name: llm-wars
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip=23.3
  - pip:
    - rich>=13.7.0
    - python-dotenv>=1.0.0
    - openai>=1.0.0
    - anthropic>=0.5.0
    - google-generativeai>=0.3.0
    - asyncio
    - tenacity
    - aiohttp